title: Lynn Zheng's Portfolio Website
description: >- # this means to ignore newlines until "baseurl:"
  This site displays Lynn Zheng's projects, work experiences, internships,
  extracurricular activities, hobbies, and skills.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
analytics: UA-148352460-2

# Build settings
markdown: kramdown
# plugins:
#   - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - website.sublime-project
  - website.sublime-workspace

collections:
  resume: